### PR TITLE
Features/transactions

### PR DESCRIPTION
**Pull request by hansderly**
In this PR, I:
✅ Added a column species of type string to the animals' table.
✅ Added data to the animals' table.
✅ Used transactions to Update, Delete data from the animals' table.
✅ Added queries to give statics of animals
✅ Added screenshot pdf file

[SCREENSHOT LINK](https://docs.google.com/document/d/1M8uqPBce7e6KoBo7mXAxPAdVNuA5cqTji5DXCEfssXk/edit?usp=sharing)

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
### Hi @hansderly, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- [ ] Correct Git-flow followed :100: 
- [ ] Transactions created :rocket: 

## Required Changes ♻️
_Check the comments under the review._
- [ ] It would be better if we add a new column called `species` to our Animals table. Hint: Kindly use the `Alter` command
- [ ] It would be better if we add our name to the MIT License file so that it show how professional our project is. Also, kindly remove the live link in our README file since the link is broken and misleading
- [ ] It would be better if we add the screenshots of our query results to our PR

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Gambit142 — CHANGES_REQUESTED** [review]
Hi @hansderly 👋, 

Great work on making the changes requested by a previous reviewer 👏 

### Highlights
- Everything that creates or changes the table's structure is saved in the schema.sql file ✔️ 
- Everything that populates tables with data is saved in the data.sql file ✔️ 
- Everything that is a query that helps to analyze data is saved in the queries.sql file ✔️ 

You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

 ## Required Changes ♻️
### - [ ] One of the requirements is to add screenshots of the transactions and results of queries. The first reviewer requested this change. Kindly update your pull request with the screenshots


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by hansderly** [comment]
Hi @Gambit142 ,
I already add the Transaction.pdf file from the first pull request
I re add it again now
Can you please check it?

**Comment by hansderly** [comment]
@Gambit142 , I think @addod19 didn't see it, you can take a look and see the TRANSACTION.PDF file
Now that i re add it you can see 2 file that contain the screenshot of the queries.
The TRANSACTION.PDF one and the TRANSACTION_RESULT.PDF that i just add now.

**Comment by hansderly** [comment]
@addod19 , @Gambit142  Please, verify before i submit for another review, because i only left with one review,
Thank you.

**Comment by hansderly** [comment]
@addod19 , @Gambit142 can you please verify that the "feature/tansactions/ branch contain the Transaction.pdf file please?

**Comment by Gambit142** [comment]
Hi @hansderly 👋, based on the requirement, kindly add the screenshot to the Pull request description. See the screenshot below:

image

**Comment by hansderly** [comment]
> Hi @hansderly 👋, based on the requirement, kindly add the screenshot to the Pull request description. See the screenshot below:
> 
> image

Thanks for clarifying that

**Review by PinkMoon25 — APPROVED** [review]
Hi @hansderly, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
Gitflow :heavy_check_mark: 
Update animal table :heavy_check_mark: 
Readme :heavy_check_mark: 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
